### ISSUE TITLE
Gulp deploy error

### ISSUE THREAD

**Issue by tejasmanohar** [appupa/website#26]
```
gulp deploy
Error: Error: Command failed: fatal: repository 'undefined' does not exist
```

fix?

**Comment by tejasmanohar** [comment]
add git remote, include this in contributing guide

**Comment by tejasmanohar** [comment]
nvm @simplyianm still an issue, site is hardcoded in code

**Comment by tejasmanohar** [comment]
https://gist.github.com/tejasmanohar/d7257615eb4a42181c3e#file-gistfile1-js-L55 not working either @simplyianm

**Comment by simplyianm** [comment]
you dumb
