### ISSUE TITLE
Add slider to the portfolio section

### ISSUE THREAD

**Issue by piedoom** [appupa/website#45]
Add a slider to the portfolio section of the site for easier navigation.

**Comment by tejasmanohar** [comment]
@piedoom - think you can get this done by end of tomorrow (01/22/15)?

**Comment by tejasmanohar** [comment]
goal is to have this completed by EOD feb 7

**Comment by tejasmanohar** [comment]
@simplyianm do this

**Comment by tejasmanohar** [comment]
*ping* @simplyianm

**Comment by simplyianm** [comment]
How
